USE [master]
GO


CREATE DATABASE [CURSO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CURSO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CURSO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CURSO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CURSO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CURSO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CURSO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CURSO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CURSO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CURSO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CURSO] SET ARITHABORT OFF 
GO

ALTER DATABASE [CURSO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CURSO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CURSO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CURSO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CURSO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CURSO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CURSO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CURSO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CURSO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CURSO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CURSO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CURSO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CURSO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CURSO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CURSO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CURSO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CURSO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CURSO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CURSO] SET  MULTI_USER 
GO

ALTER DATABASE [CURSO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CURSO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CURSO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CURSO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CURSO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CURSO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CURSO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CURSO] SET  READ_WRITE 
GO


