USE NERDDOSDADOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'VIDEOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE VIDEOS
	END


	
CREATE TABLE VIDEOS (
ID_VIDEO		INTEGER IDENTITY (1,1),
TITULO			VARCHAR(100),
CATEGORIA		VARCHAR(100),
DATA_VIDEO		DATE)



INSERT INTO VIDEOS VALUES ('COMO FAZER NORMALIZAÇÃO E PADRONIZAÇÃO DE DADOS', 'MACHINE LEARNING','2022-07-10')
INSERT INTO VIDEOS VALUES ('COMO FAZER UM MODELO DE CLUSTERIZAÇÃO', 'MACHINE LEARNING','2022-08-10')
INSERT INTO VIDEOS VALUES ('COMO APRENDER PYTHON DO ZERO', 'PYTHON','2022-07-15')
INSERT INTO VIDEOS VALUES ('COMO APRENDER POWER BI DO ZERO', 'VISUALIZAÇÃO DE DADOS','2022-09-10')
INSERT INTO VIDEOS VALUES ('COMO COMEÇAR EM CIENCIA DE DADOS', 'CIENCIA DE DADOS','2022-10-10')


SELECT * FROM VIDEOS

SELECT * FROM VIDEOS ORDER BY DATA_VIDEO

SELECT * FROM VIDEOS ORDER BY DATA_VIDEO DESC


SELECT
ID_VIDEO,
TITULO,
CONVERT(VARCHAR(10),DATA_VIDEO,103) AS DATA
FROM VIDEOS
ORDER BY DATA_VIDEO DESC
