USE NERDDOSDADOS
GO


CREATE TABLE VIDEOS (
ID_VIDEO		INTEGER,
TITULO			VARCHAR(100),		
CATEGORIA		VARCHAR(100))



INSERT INTO VIDEOS VALUES (1, 'COMO FAZER NORMALIZAÇÃO E PADRONIZAÇÃO DE DADOS', 'MACHINE LEARNING')
INSERT INTO VIDEOS VALUES (2, 'COMO FAZER UM MODELO DE CLUSTERIZAÇÃO', 'MACHINE LEARNING')
INSERT INTO VIDEOS VALUES (3, 'COMO APRENDER PYTHON DO ZERO', 'PYTHON')
INSERT INTO VIDEOS VALUES (4, 'COMO APRENDER POWER BI DO ZERO', 'VISUALIZAÇÃO DE DADOS')
INSERT INTO VIDEOS VALUES (5, 'COMO COMEÇAR EM CIENCIA DE DADOS', 'CIENCIA DE DADOS')


SELECT * FROM VIDEOS

SELECT ID_VIDEO,TITULO FROM VIDEOS WHERE ID_VIDEO IN(1,2)

SELECT * FROM VIDEOS WHERE CATEGORIA = 'MACHINE LEARNING'

SELECT * FROM VIDEOS WHERE CATEGORIA LIKE '%MACH%'



UPDATE VIDEOS SET TITULO = 'COMO APRENDER PYTHON DO ZERO EM UMA AULA'  WHERE ID_VIDEO = 3

SELECT * FROM VIDEOS 


BEGIN TRAN
	UPDATE VIDEOS SET TITULO = 'COMO APRENDER PYTHON DO ZERO EM UMA AULA - TESTE' WHERE ID_VIDEO = 3
--COMMIT
--ROLLBACK

--APRENDENDO SQL DO ZERO

SELECT * FROM VIDEOS 


DELETE FROM VIDEOS WHERE ID_VIDEO = 3
SELECT * FROM VIDEOS



TRUNCATE TABLE VIDEOS




