USE NERDDOSDADOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PRODUTOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE PRODUTOS
	END

		
CREATE TABLE PRODUTOS (
ID_PRODUTO		INTEGER IDENTITY (1,1),
DESCRICAO		VARCHAR(100),
VALOR			NUMERIC(10,2)) --9999999999.99



INSERT INTO PRODUTOS VALUES ('CHOCOLATE', 10)
INSERT INTO PRODUTOS VALUES ('FRUTAS', 12)
INSERT INTO PRODUTOS VALUES ('IOGURTE', 8)
INSERT INTO PRODUTOS VALUES ('ARROZ', 15)
INSERT INTO PRODUTOS VALUES ('FEIJÃO', 9)


SELECT * FROM PRODUTOS 

DELETE FROM PRODUTOS WHERE ID_PRODUTO = 5

SELECT * FROM PRODUTOS 