USE NERDDOSDADOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'VIDEOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE VIDEOS
	END


	
CREATE TABLE VIDEOS (
ID_VIDEO		INTEGER IDENTITY (1,1),
TITULO			VARCHAR(100),		
CATEGORIA		VARCHAR(100))



INSERT INTO VIDEOS VALUES ('COMO FAZER NORMALIZAÇÃO E PADRONIZAÇÃO DE DADOS', 'MACHINE LEARNING')
INSERT INTO VIDEOS VALUES ('COMO FAZER UM MODELO DE CLUSTERIZAÇÃO', 'MACHINE LEARNING')
INSERT INTO VIDEOS VALUES ('COMO APRENDER PYTHON DO ZERO', 'PYTHON')
INSERT INTO VIDEOS VALUES ('COMO APRENDER POWER BI DO ZERO', 'VISUALIZAÇÃO DE DADOS')
INSERT INTO VIDEOS VALUES ('COMO COMEÇAR EM CIENCIA DE DADOS', 'CIENCIA DE DADOS')


SELECT * FROM VIDEOS

SELECT * FROM VIDEOS WHERE ID_VIDEO = 1

SELECT * FROM VIDEOS WHERE CATEGORIA = 'MACHINE LEARNING'

SELECT * FROM VIDEOS WHERE CATEGORIA LIKE '%MACHINE%'

SELECT * FROM VIDEOS WHERE TITULO LIKE '%APRENDER%'


UPDATE VIDEOS SET TITULO = 'COMO APRENDER PYTHON DO ZERO EM UMA AULA' WHERE ID_VIDEO = 3

SELECT * FROM VIDEOS 


DELETE FROM VIDEOS WHERE ID_VIDEO = 3


SELECT * FROM VIDEOS 







