--CONSULTANDO CLIENTES, TELEFONE E TIPO_TELEFONE
SELECT 
*
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)



--OBTENDO SÓ OS CAMPOS NECESSÁRIOS
SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
B.DDD,
B.TELEFONE,
C.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)


--ORDENANDO A CONSULTA
SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
B.DDD,
B.TELEFONE,
C.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)
ORDER BY A.NOME


--CONSULTANDO DADOS COM INNER JOIN E WHERE
SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
B.DDD,
B.TELEFONE,
C.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)
WHERE C.DESCRICAO = 'CELULAR'
ORDER BY A.NOME


SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
B.DDD,
B.TELEFONE,
C.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)
WHERE C.ID_TIPO_TELEFONE = 1
ORDER BY A.NOME

SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
B.DDD,
B.TELEFONE,
C.DESCRICAO AS TIPO_TELEFONE
FROM CLIENTES A(NOLOCK)
INNER JOIN TELEFONES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
INNER JOIN TIPO_TELEFONE C(NOLOCK) ON (C.ID_TIPO_TELEFONE = B.ID_TIPO_TELEFONE)
WHERE A.TIPO_PESSOA = 'J'
ORDER BY A.NOME