--INNER JOIN
SELECT
A.ID_PRODUTO,
A.DESCRICAO,
B.ID_PEDIDO,
B.DATA_PEDIDO,
B.QUANTIDADE,
B.VALOR_TOTAL
FROM PRODUTOS A(NOLOCK)
INNER JOIN PEDIDOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)



--LEFT JOIN
SELECT
A.ID_PRODUTO,
A.DESCRICAO,
B.ID_PEDIDO,
B.DATA_PEDIDO,
B.QUANTIDADE,
B.VALOR_TOTAL
FROM PRODUTOS A(NOLOCK)
LEFT JOIN PEDIDOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)


--RIGHT JOIN
SELECT
A.ID_PEDIDO,
A.DATA_PEDIDO,
A.DATA_ENTREGA,
B.DESCRICAO AS PRODUTO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
RIGHT JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)


