--SELECT SIMPLES DOS NOSSOS CLIENTES
SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA
FROM CLIENTES A(NOLOCK)




--UTILIZANDO UM SUB SELECT
SELECT 
A.ID_CLIENTE,
A.NOME,
A.TIPO_PESSOA,
(SELECT COUNT(*) FROM PEDIDOS B(NOLOCK) where B.ID_CLIENTE = A.ID_CLIENTE) AS QTD_PEDIDOS 
FROM CLIENTES A(NOLOCK)





--UTILIZANDO UM SUB SELECT (nesse caso melhor usar o Inner para não fazer 2 sub selects)
SELECT
A.ID_PEDIDO,
(SELECT B.DESCRICAO FROM PRODUTOS B(NOLOCK) WHERE B.ID_PRODUTO = A.ID_PRODUTO) AS DESCRICAO,
(SELECT B.VALOR_UNITARIO FROM PRODUTOS B(NOLOCK) WHERE B.ID_PRODUTO = A.ID_PRODUTO) AS VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)








SELECT
A.ID_PEDIDO,
B.DESCRICAO,
B.VALOR_UNITARIO,
A.QUANTIDADE,
A.VALOR_TOTAL
FROM PEDIDOS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)