--LEMBRE-SE DO EXEMPLO DE UPDATE SIMPLES...
USE CURSO
GO

SELECT * FROM PRODUTOS

UPDATE PRODUTOS SET DESCRICAO = 'BERMUDA' WHERE ID_PRODUTO = 2;

UPDATE PRODUTOS SET DESCRICAO = 'MEIA SOCIAL' WHERE ID_PRODUTO = 7;
 
 SELECT * FROM CLIENTES

--UPDATE COM INNER JOIN
SELECT * FROM TELEFONES A
INNER JOIN TIPO_TELEFONE B(NOLOCK) ON (B.ID_TIPO_TELEFONE=A.ID_TIPO_TELEFONE)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
WHERE C.NOME = 'JOAQUIM DA SILVA SANTOS'
AND B.DESCRICAO = 'CELULAR'



UPDATE A SET DDD = 11
FROM TELEFONES A
INNER JOIN TIPO_TELEFONE B(NOLOCK) ON (B.ID_TIPO_TELEFONE=A.ID_TIPO_TELEFONE)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
WHERE C.NOME = 'JOAQUIM DA SILVA SANTOS'
AND B.DESCRICAO = 'CELULAR'
