SELECT
A.ID_PEDIDO,
A.ID_CLIENTE,
A.ID_PRODUTO,
A.DATA_PEDIDO,
A.QUANTIDADE,
B.VALOR_UNITARIO,

--OPERADOR DE MULTIPLICAÇÃO
A.QUANTIDADE * B.VALOR_UNITARIO AS VALOR_TOTAL_PEDIDO,

--OPERADOR DE DIVISAO
B.VALOR_UNITARIO / 2 AS PRECO_COMPRA,

--PERCENTUAL
15 * B.VALOR_UNITARIO / 100 AS PERCENTUAL,

--ADIÇÃO
B.VALOR_UNITARIO + (15 * B.VALOR_UNITARIO / 100) AS NOVA_MARGEM_LUCRO,


--SUBTRAÇÃO
B.VALOR_UNITARIO - (15 * B.VALOR_UNITARIO / 100) AS NOVA_MARGEM_DESCONTO




FROM PEDIDOS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)